name: Test Artifact Workflow

on:
  workflow_dispatch:

jobs:
  test-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate test files
        run: |
          mkdir -p output

          echo "Hello GitHub Actions" > output/summary.md
          date > output/summary.md


      - name: Show generated files
        run: |
          ls -lah output
          cat output/summary.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: output/
          retention-days: 7
          
      - name: sleep
        run: sleep 5h
